name: Pull request sonar java
on: 
  push:
    branches:
      - main
  workflow_call:   
    secrets:
      SONARQUBE_DEV_URL:
        required: true
      SONARQUBE_DEV_TOKEN:
        required: true 
      TOKEN_REPO_TEMPLATE:
        required: false 

jobs:
  sonar:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2.4.0
        with:
            java-version: '11' # The JDK version to make available on the path.
            java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
            architecture: x64
            distribution: temurin
            #cache: 'maven'

      - name: Sonarqube
        run: mvn verify sonar:sonar -DskipTests -Dsonar.host.url=${{ secrets.SONARQUBE_DEV_URL }} -Dsonar.login=${{ secrets.SONARQUBE_DEV_TOKEN }}
      - name: Read value from Properties-file check Quality Gate
        id: read_property
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: './target/sonar/report-task.txt'
          property: 'ceTaskId'
      - name: Show ceTaskId
        run: echo ${{ steps.read_property.outputs.value }}
      - name: Show Github ref
        run: echo ${{ github.ref }}
      - name: mostrar
        run: |
          echo ${{ github.ref }}
          tree
      
#       - uses: actions/checkout@v2
#         with:
#           repository: 'Blue-Express/bx_templates'
#           path: 'templates'
#           ref: 'refs/heads/blue'
#           token: ${{ secrets.TOKEN_REPO_TEMPLATE }}
      
      - name: Break Build Quality Gate
        run: |
          pwd
          ls
          sh ./break_build.sh ${{ secrets.SONARQUBE_DEV_URL }} ${{ secrets.SONARQUBE_DEV_TOKEN }} ${{ steps.read_property.outputs.value }}
